### ISSUE TITLE
Add some basic CSS

### ISSUE THREAD

**Issue by MadeByMike** [andybelldesign/hebra#3]
@andybelldesign how do you feel about adding some basic CSS? 

I know this is meant to be very... skeletal 🦴, but it is meant to be a scaffold\boilerplate and to add some I need to create a directory  and add a pass-through. 

I was thinking it might be a slightly better starting point to include a basic stylesheet for people to edit. It would probably have a reset and not much else.

Will make a PR if you're agreeable. Will close if not :)

**Comment by Andy-set-studio** [comment]
Howdy! I’m going to keep this as a pure HTML setup. You could fork it and add some basic CSS though. 

The other option is that you could start with this one: https://github.com/andybelldesign/hylia
